### ISSUE TITLE
no artifacts found

### ISSUE THREAD

**Issue by MVersteijlen** [adhusch/PaCER#1]
Dear Andreas Husch,
I'm trying to run PaCER on a post op CT, which was initally a DICOM file.
I transfered it to nifti using dcm2nii, and then resliced it using the reslice_nii function.
When I run PaCER with mask, it detects no artifacts, with mask it detects 876, of which 0 are found to be electrodes. I think it might be because of the cc analysis, that it expects more round artifacts for electrodes. Is there a way to alter this to make it more sensitive to other shapes? Or does it mean the quality of the CT images isn't good enough?
Thank you for making your code publicly available!
Kind Regards,
Monique

**Comment by adhusch** [comment]
Dear Monique,

sorry to hear that it didn't work out of the box in your case.

I guess you did the re-slicing because of non-orthogonal headers? 

Could you provide an anonymized example CT so i could have a look at the data? 

Currently the included automatic brain mask estimation is not super robust on CTs acquired with certain less common filters/reconstruction kernels or thick slices, however PaCER itself (i.e. the electrode reconstruction) should work.
The "noMask" option is mainly meant for phantom scans, on "real data" i will lead to cable parts outside the brain interfering with the electrode detection. 
You could try to manually provide a brain mask in such a case (for example estimated by a more complex tool like BET on a co-registered T1) using the "brainMask" option. For this a very rough mask will do, the only requirement is that it contains the electrodes (and not the cables), i.e. as a trick you could also do a very rough manual segmentation of the electrode area and provide this as a "brainMask".

Please keep me posted, your feedback will help to make the preprocessing more reliable for more people.

Best
Andreas

**Comment by adhusch** [comment]
-Pushed patch for polyArcLength3 assertion violation (numeric accuracy issue)
-Pushed improvements for extremely noisy brain tissue in CT data (for example reconstructed with "bone filter") recursing the electrode pointcloud detection with decreasing METAL_THRESHOLD.
